Hakondate/Hakondate

lib/model/user/user_model.dart, lib/model/user/user_model.g.dart
=> User model

lib/main.dart, lib/provider/menu/menu_state.dart, lib/provider/menu/menu_state.freezed.dart, lib/provider/user/user_state.dart, lib/provider/user/user_state.freezed.dart
freezedを用いたStateクラスの生成
- menu_state
- user_state
=> Menu state

lib/view/splash.dart, lib/view_model/menu/menus_view_model.dart
=> [refact]Splash initのリファクタリング

lib/repository/local/database_manager.dart
=> [add]UPDATEの処理を記述

lib/router/app_navigator_state_notifier.dart, lib/state/navigator/app_navigator_state.freezed.dart, lib/state/splash/splash_state.dart, lib/state/splash/splash_state.freezed.dart, lib/state/terms/terms_state.dart, lib/state/terms/terms_state.freezed.dart, lib/view/splash.dart, lib/view/terms.dart, lib/view_model/is_agreed_view_model.dart, lib/view_model/menus_view_model.dart, lib/view_model/splash_view_model.dart, lib/view_model/terms_view_model.dart
SplashのError Dialog周りの遷移が管理されていなかったので修正  
それに合わせて複数箇所の実装方法変更
=> Splash errordialog

lib/model/dish/dish_category.dart, lib/model/dish/dish_model.dart, lib/model/nutrients/nutrient_unit.dart, lib/model/school/school_classification.dart, lib/model/school/school_model.dart, lib/repository/local/menus_local_repository.dart, lib/state/splash/loading_status.dart, lib/state/splash/splash_state.dart, lib/state/user/school_grade.dart, lib/state/user/user_state.dart, lib/view/component/label/nutrient_label.dart, lib/view/component/label/nutrients_list.dart, lib/view_model/multi_page/common_function.dart, lib/view_model/multi_page/user_view_model.dart, lib/view_model/single_page/splash_view_model.dart
該当なし
- 巴中以外を選ぶとメニューが読み込めないエラーの解消
- 定数値を別ファイルにするリファクタリング
- 特になし
=> 給食の読み込みロジックの変更とenumの整理

lib/view/calendar/calendar.dart, lib/view/component/other/loading_animation_widget.dart, lib/view/daily/daily.dart, lib/view_model/single_page/daily_view_model.dart
**Issueリンク**
#59 
**実装したこと**
- カレンダーを更新してもデイリー側で適用されていなかった問題を解決
**実装しなかったこと**
- 特になし
**スクリーンショット**
**補足事項**
- 特になし
=> カレンダーを更新してもデイリー側で適用されていなかった問題を解決

.github/workflows/run_build_runner.yml
**実装したこと**
- 上手くGitHub Actionsが動いていないので修正
**実装しなかったこと**
- 特になし
**スクリーンショット**
**補足事項**
- 特になし
**セルフレビュー**
- ファイル末尾の改行
- Widgetの階層構造
- 静的型付け
くらいは少なくとも確認する
=> workflowの修正

android/app/build.gradle, android/build.gradle, android/gradle/wrapper/gradle-wrapper.properties
**Issueリンク**
#130 #131
**実装したこと**
**実装しなかったこと**
- 特になし
**スクリーンショット**
Log
```
Launching lib/main.dart on sdk gphone64 arm64 in debug mode...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
W/FlutterActivityAndFragmentDelegate( 7789): A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.
Connecting to VM Service at ws://127.0.0.1:55349/4bvioWZxJ5M=/ws
W/DynamiteModule( 7789): Local module descriptor class for com.google.android.gms.providerinstaller.dynamite not found.
I/DynamiteModule( 7789): Considering local module com.google.android.gms.providerinstaller.dynamite:0 and remote module com.google.android.gms.providerinstaller.dynamite:0
W/ProviderInstaller( 7789): Failed to load providerinstaller module: No …
```
=> Androidの無警告ビルド

renovate.json5
=> Renovateの設定更新

renovate.json5
**Issueリンク**
#
**実装したこと**
**実装しなかったこと**
- 特になし
**スクリーンショット**
**補足事項**
- 特になし
**チェックリスト**
=> Renovate Reconfigure

lib/repository/remote/menus/menus_remote_repository.dart, lib/view/bottom_bar/app_bottom_navigation_bar.dart, lib/view_model/single_page/splash/splash_view_model.dart
**Issueリンク**
**実装したこと**
**実装しなかったこと**
- 特になし
**スクリーンショット**
**補足事項**
- 特になし
**チェックリスト**
=> お便り機能のプロダクションとステージング環境での無効化

lib/view_model/multi_page/user/user_view_model.dart, lib/view_model/multi_page/user/user_view_model.g.dart, lib/view_model/single_page/daily/daily_view_model.dart, lib/view_model/single_page/daily/daily_view_model.g.dart
**Issueリンク**
#
**実装したこと**
**実装しなかったこと**
- 特になし
**スクリーンショット**
**補足事項**
- 特になし
**チェックリスト**
=> hotfix: DailyVMのBuildに失敗する問題の解消

lib/view/license/license.dart, lib/view/license/license_detail.dart
**Issueリンク**
#203 
**実装したこと**
**実装しなかったこと**
- 特になし
**スクリーンショット**
**補足事項**
- 特になし
**チェックリスト**
=> refactor: import packages license info

renovate.json5
**Issueリンク**
#206 
**実装したこと**
**実装しなかったこと**
- 特になし
**スクリーンショット**
**補足事項**
- 特になし
**チェックリスト**
=> fix: renovate settings

README.md, android/app/build.gradle
**Issueリンク**
#
**実装したこと**
**実装しなかったこと**
- 特になし
**スクリーンショット**
**補足事項**
- 特になし
**チェックリスト**
=> add signingConfigs to app/build.gradle

pubspec.yaml
**Issueリンク**
#
**実装したこと**
**実装しなかったこと**
- 特になし
**スクリーンショット**
**補足事項**
- 特になし
**チェックリスト**
=> Release 2.0.2

pubspec.yaml
**Issueリンク**
#
**実装したこと**
**実装しなかったこと**
- 特になし
**スクリーンショット**
**補足事項**
- 特になし
**チェックリスト**
=> バージョンコードを戻す

lib/view/component/graph/nutrients_radar_chart.dart, lib/view/daily/nutrients_card.dart, lib/view/dictionary/dictionary_item.dart, lib/view_model/single_page/daily/daily_graph_view_model.dart, lib/view_model/single_page/daily/daily_graph_view_model.g.dart, lib/view_model/single_page/daily/daily_view_model.dart, lib/view_model/single_page/daily/daily_view_model.g.dart
**Issueリンク**
#
**実装したこと**
**実装しなかったこと**
- 特になし
**スクリーンショット**
**補足事項**
- 特になし
**チェックリスト**
=> ホーム画面のパフォーマンス向上とバグの修正

android/app/build.gradle
**Issueリンク**
#228
**実装したこと**
**実装しなかったこと**
- 特になし
**スクリーンショット**
**補足事項**
- レビューはandroidが問題なく起動できることを確認するだけで良い
**チェックリスト**
=> targetSdk versionを34にあげる

lib/view/dictionary/recommend_foodstuff.dart, lib/view_model/single_page/daily/daily_recommend_foodstuffs_view_model.dart, lib/view_model/single_page/daily/daily_recommend_foodstuffs_view_model.g.dart
**Issueリンク**
なし
**実装したこと**
**実装しなかったこと**
- 特になし
**スクリーンショット**
**補足事項**
- 特になし
**チェックリスト**
=> おすすめ食材が表示されない問題を修正

lib/repository/local/sqlite/dictionary_items/dictionary_items_local_repository.dart, lib/view/dictionary/recommend_foodstuff.dart
**Issueリンク**
#199 
**実装したこと**
**実装しなかったこと**
- 特になし
**スクリーンショット**
**補足事項**
-食材の合計種類数は2477種類
-3, 14, 15, 16, 17, 18群を排除した食材の合計種類数は1970種類
- 特になし
**チェックリスト**
=> おすすめ食材上位100個からランダムで5個選出

pubspec.yaml
**Issueリンク**
#
**実装したこと**
**実装しなかったこと**
- 特になし
**スクリーンショット**
**補足事項**
- 特になし
**チェックリスト**
=> バージョンアップ 2.0.2 -> 2.0.3

.metadata, lib/view/component/label/nutrient_label.dart
**Issueリンク**
#
**実装したこと**
メニューの文字が多い時に改行することでメニューが表示されるようになること
改行した時に文字が書かれている枠が大きくなること
**実装しなかったこと**
- 特になし
**スクリーンショット**
**補足事項**
- 特になし
**チェックリスト**
=> 給食のメニューの文字が多い時に改行する

pubspec.yaml
**Issueリンク**
#
**実装したこと**
**実装しなかったこと**
- 特になし
**スクリーンショット**
**補足事項**
- 特になし
**チェックリスト**
=> version up

lib/view/daily/nutrients_card.dart
…and error display
**Issueリンク**
#239
**実装したこと**
**実装しなかったこと**
- 特になし
**スクリーンショット**
**確認項目**
**補足事項**
- 特になし
**チェックリスト**
=> 日付を変えた際に，栄養素のグラフがちらつく問題を解決した
